# Generated by Django 3.2.4 on 2022-11-16 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgame',
            name='status',
            field=models.CharField(default='Ongoing', max_length=100),
        ),
    ]
