# Generated by Django 3.2.4 on 2022-11-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_chessgame_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessgame',
            name='black_player_name',
            field=models.CharField(default='Mike', max_length=100),
        ),
        migrations.AddField(
            model_name='chessgame',
            name='white_player_name',
            field=models.CharField(default='John', max_length=100),
        ),
    ]
